### ISSUE TITLE
Baseline Requirements: Update CAA from 6844 to 8659

### ISSUE THREAD

**Issue by sleevi** [cabforum/documents#168]
The Baseline Requirements currently refer to RFC 6844 as modified by Errata.

This should be updated to depen on RFC 8659, which can be done without errata.

**Comment by CBonnell** [comment]
We can also remove the verbiage added by ballot 219 ("CAs MAY treat a non-empty CAA Resource Record Set that does not contain any issue property tags (and also does not contain any issuewild property tags when performing CAA processing for a Wildcard Domain Name) as permission to issue, provided that no records in the CAA Resource Record Set otherwise prohibit issuance."), since RFC 8659 explicitly specifies the handling of that scenario.
