### ISSUE TITLE
Tag specific versions of the BRGs

### ISSUE THREAD

**Issue by RufusJWB** [cabforum/documents#81]
It would be very helpful if you would [tag](https://help.github.com/articles/working-with-tags/) the commits that reflect a specific version of the BRG. For example you could tag [this](https://github.com/cabforum/documents/commit/6f3beab8b75f6f5f5f80948718b3e896250334d0) commit with the tag `v1.5.1`  . This would make life easier preparing the annual BRG audit.

**Comment by sleevi** [comment]
Could you explain more why it would be helpful?

As a workmode, it tends to presume that there will never be multiple
ballots as a single commit, which isn’t something we’ve adopted yet.

That’s not to say we couldn’t - but what’s the use case, and more
importantly, how does it play into the audit, which should always be using
the most recently adopted version as part of the CA’s procedures, and the
specifically versioned audit criteria from the auditor.

**Comment by RufusJWB** [comment]
Regarding the version:
Of course the audit needs to follow the most recently adopted version. No doubts about that.

Regarding the use case:
I use GIT as a document versioning system for tracking our BRG audit documentation. The BRGs are linked as a submodule into my repository. By that I can be sure that we always have the latest version of the BRGs together with the audit documentation. What I would like to do is tag for every change in the BRGs (v1.5.1, v1.5.2, ...) the corresponding version of my documents so that we later can easily go back to a specific version and have everything together. As a work around I now have linked a specific branch of this rep into my repo (e.g. https://github.com/cabforum/documents/tree/Ballot-197-Changes). It's a work around that works, but it simply doesn't feel  like the GIT way of doing this.

**Comment by sleevi** [comment]
You are correct that it is not the Git way of doing things, but I believe
the Forum bylaws inherently mean that you will not be able to achieve that
flow. That is due to the necessity to commit the changes prior to the IP
Review completing.

Given the current workmode of the Forum, where the current “master” remains
a Word document, and given the Bylaws, it is best to use the canonical
published URLs of the BRs for artifact resolution - e.g.
https://cabforum.org/wp-content/uploads/CA-Browser-Forum-BR-1.5.4.pdf

Current members have been somewhat vocally oppposed to improvements in this
regard, such as formally specifying the process for changes, thus such URLs
maintainnthe incumbent advantage of “how we’ve done things”

**Comment by RufusJWB** [comment]
I'll close this issue.
