### ISSUE TITLE
Update 3.2.2.4 for Applicants that are Individual Natural Persons

### ISSUE THREAD

**Issue by dzacharo** [cabforum/documents#96]
The current BRs in 3.2.2.4 state that
"For purposes of domain validation, the term Applicant includes the Applicant's Parent Company, Subsidiary Company, or Affiliate."

Since the adoption of IV Certificates, this sentence should include Applicants that are Individual Natural Persons. Here is a proposed amendment.

"For purposes of domain validation, the term Applicant includes the Applicant's Parent Company, Subsidiary Company, Affiliate or the Applicant as an individual Natural Person".

**Comment by timfromdigicert** [comment]
True.  I'd put it in the spring cleanup branch, but a little corner of my brain is worried some people might think it is too substantive for that.

**Comment by sleevi** [comment]
This change is not necessary. Section 1.6.1 clearly addresses this.

Applicant: The natural person or Legal Entity that applies for (or seeks renewal of) a Certificate. Once the Certificate issues, the Applicant is referred to as the Subscriber. 

The cited section expands that definition for purposes of domain validation, but does not replace, and the definition is already sufficient. We should close this issue.

**Comment by timfromdigicert** [comment]
Shouldn't we at least consider fixing 3.2.2.4 so it doesn't attempt to redefine a defined term?  Now that I'm looking at the language, it's really really weird.

**Comment by sleevi** [comment]
Could you explain why you believe it's a redefinition, and why you find it really, really weird?

This is taking a term, and extending it for a limited scope. I think it'd be far more damaging and detrimental to try to introduce Yet Another Term just for this section, and I would find it really really weird as proposed, because it would be adding further ambiguity by only partially covering the definition.

I really fail to see the issue here, considering it's already covered.

**Comment by timfromdigicert** [comment]
I think it is extremely confusing if a defined term means two different things depending on scope.  I've never seen any other standards document do that.  If I'm looking at a usage of Applicant, and I'm looking at the definition ...  I should be done.  I shouldn't also have to look at all the section headers to see if I'm in scope of a re-definition.  That's crazy.

**Comment by sleevi** [comment]
OK, then we should be clear that we're not talking about the problem as stated.

The problem as stated is that it does not include for IV certificates, when it clearly does, because it adds to the existing definition the list of parties considered appropriate.

Your problem is that it modifies the list of parties at all, at least based on https://github.com/cabforum/documents/issues/96#issuecomment-393553145 , and the only two solutions I can see are to either introduce yet another term or to extend the current term, both of which are things I see as more problematic than the current text. Is there an alternative you'd like to propose that you think addresses the problems as you see them?

**Comment by timfromdigicert** [comment]
Right.  I agree with you that the original problem doesn't exist, but I noticed a new problem.

I actually think we need a new term, since the section is talking about a Defined Thing which isn't the Applicant.

**Comment by dzacharo** [comment]
I agree with Tim. There are several places in the document where we have weird and not understandable language and other places where we re-define terms of 1.6.1. 

I decided to open issues instead of bringing each finding to the forum list so we will have a chance to collect a couple and then deal with them in batch mode. For the time being I will just ask for some patience until more similar issues emerge.

**Comment by dzacharo** [comment]
After some careful reading, this section is really about the Domain Validation part only. I recall previous discussions at the CA/B Forum about who the Applicant is when we actually don't have the Applicant's fullname for DV Certificates so I guess this topic requires a longer discussion that must take place back at the Forum. I will close this issue and send an email to the Validation WG to keep this topic among the items on their TODO list.

**Comment by timfromdigicert** [comment]
It's on the Trello board now:

https://trello.com/c/3oE84It5/16-definition-of-applicant-is-different-for-3224-than-it-is-for-the-rest-of-the-document
