### ISSUE TITLE
Allow Brainpool brainpoolp256r1 curve for ECC certrificates

### ISSUE THREAD

**Issue by RufusJWB** [cabforum/documents#97]
The "Bundesamt für Sicherheit in der Informationstechnik" (German Federal Office for Information Security) published a technical guidance [TR-03116-3](https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR03116/BSI-TR-03116-4.pdf?__blob=publicationFile&v=4) which defines fundamental cryptographic requirements for governmental projects. In chapter 2.1.3 it defines three curves that have to be supported as a minimum for SSL/TLS. One of this three curves is the brainpoolp256r1 curve. This curve is not allowed acc. BRGs chapter 6.1.5.

I would like to propose, that this curve becomes allowed by the BRGs as well.

**Comment by sleevi** [comment]
Hi Rufus,

Have you signed the IPR agreement? If so, this is better suggested on the CA/Browser Forum list. I'm going to close this issue, as suggestions like this should be posted there.

**Comment by RufusJWB** [comment]
Hi Ryan! I can't sign the IPR because Siemens' Legal Department has a problem with it. We have been in contact with Kirk Hall and there seems to be no easy way out of those legal problems. There might be a work-around but this will take some more time. In the meantime I was hoping that someone might pick up the proposal I'm writing here - as with other proposals / remarks I've written here - and brings it officially into the CA/B forum.

**Comment by sleevi** [comment]
The proper channel to direct this, then, is to the questions@cabforum.org
list.

**Comment by RufusJWB** [comment]
Done so. Thank you for the direction to the right channel.

**Comment by timfromdigicert** [comment]
Ryan,

 

I know others in the forum disagree, but I thought you and I were on the same page with regards to github issues being basically in the same boat as the questions list with regards to IPR issues?

 

Are you forwarding him to the questions list because you believe that is the agreed upon CABF policy?  It is true that the questions list has more mature policies, procedures and precedents; I personally would lean towards guiding people there based on that.

 

But in the future I personally would like to be able to accept and track suggestions from third parties (e.g. relying parties) in github, with the understanding that some of them might have similar IPR concerns as emails to the questions list.  We might want to tag them somehow to mark the fact they come from “unsafe individuals”.

 

One of the common complaints I hear from our customers and partners about the CA/Browser Forum is that the voices of non-CAs an non-browsers are not heard.  While I personally believe that is false, and that becoming an Interested Party is easy and anyone who cares enough should do so, I would like to see us have as many open communications channels as possible.

 

-Tim

**Comment by sleevi** [comment]
I am directing based on the defined process in our bylaws.

We support improvements to that process. But as over a year of discussions
around this topic has shown, there is not agreement as to this more
desirable work mode. Further ballots are necessary, potentially impacting
the IP policy.

**Comment by timfromdigicert** [comment]
Great, thought so.  Thank you.

 

-Tim
